import pandas as pd
from pathlib import Path


# PATH DE LOS INPUTH

PATH_INPUTS =  "datos/inputs.xlsx" 


# FECHAS

PERIODO_CONSIDERADO = pd.Timestamp('01-2025')
FECHA_PM_TTY_TBX = pd.Timestamp('01-2025') 


# CONFIG PLANTAS


CAPACIDAD_MEGA = 43
CAPACIDAD_TTY_DP = 28
CAPACIDAD_TTY_TBX = 34
CAPACIDAD_BASE_CONVERTIBLE_TBX = 13.2
CAPACIDAD_ADICIONAL_TBX = 20.2
CAPACIDAD_EVACUACION_MEGA = 5600
CAPACIDAD_EVACUACION_TTY_DP = 200
CAPACIDAD_EVACUACION_TTY_TBX = 7700

MAX_DERIVACION_TTY_DP_A_MEGA = 5
MAX_DERIVACION_TTY_TBX_A_TTY_DP = CAPACIDAD_TTY_DP - CAPACIDAD_BASE_CONVERTIBLE_TBX




# BOOL SAVE

GUARDAR_CSVS = True